package day42_ExceptionContinues;

public class ThrowsKeyword2 {
    public static void main(String[] args) throws ArithmeticException{

        System.out.println("Test Started");
        System.out.println(8/0);
        System.out.println("Test Complete");

    }
}
